// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodkarpackiLekarz.Infrastructure.Persistence;

#nullable disable

namespace PodkarpackiLekarz.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PLA")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PodkarpackiLekarz.Core.Users.Doctors.DoctorType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DoctorTypes", "PLA");
                });

            modelBuilder.Entity("PodkarpackiLekarz.Core.Users.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IdentityUsers", "PLA");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PodkarpackiLekarz.Core.Users.Doctors.Doctor", b =>
                {
                    b.HasBaseType("PodkarpackiLekarz.Core.Users.IdentityUser");

                    b.Property<bool>("CredibilityConfirmed")
                        .HasColumnType("bit");

                    b.ToTable("Doctors", "PLA");
                });

            modelBuilder.Entity("PodkarpackiLekarz.Core.Users.Doctors.Doctor", b =>
                {
                    b.HasOne("PodkarpackiLekarz.Core.Users.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("PodkarpackiLekarz.Core.Users.Doctors.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PodkarpackiLekarz.Core.Users.Doctors.DoctorProfile", "DoctorProfile", b1 =>
                        {
                            b1.Property<Guid>("identityUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("DoctorTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("identityUserId");

                            b1.HasIndex("DoctorTypeId");

                            b1.ToTable("DoctorProfiles", "PLA");

                            b1.HasOne("PodkarpackiLekarz.Core.Users.Doctors.DoctorType", "DoctorType")
                                .WithMany()
                                .HasForeignKey("DoctorTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("identityUserId");

                            b1.Navigation("DoctorType");
                        });

                    b.Navigation("DoctorProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
